// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: music.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Server {
  /// <summary>
  /// The music service definition.
  /// </summary>
  public static partial class MusicService
  {
    static readonly string __ServiceName = "music.MusicService";

    static readonly grpc::Marshaller<global::Server.AlbumRequest> __Marshaller_music_AlbumRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Server.AlbumRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Server.AlbumDetails> __Marshaller_music_AlbumDetails = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Server.AlbumDetails.Parser.ParseFrom);

    static readonly grpc::Method<global::Server.AlbumRequest, global::Server.AlbumDetails> __Method_GetAlbumDetails = new grpc::Method<global::Server.AlbumRequest, global::Server.AlbumDetails>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAlbumDetails",
        __Marshaller_music_AlbumRequest,
        __Marshaller_music_AlbumDetails);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Server.MusicReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MusicService</summary>
    [grpc::BindServiceMethod(typeof(MusicService), "BindService")]
    public abstract partial class MusicServiceBase
    {
      /// <summary>
      /// Sends a music request
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Server.AlbumDetails> GetAlbumDetails(global::Server.AlbumRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MusicService</summary>
    public partial class MusicServiceClient : grpc::ClientBase<MusicServiceClient>
    {
      /// <summary>Creates a new client for MusicService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MusicServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MusicService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MusicServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MusicServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MusicServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sends a music request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Server.AlbumDetails GetAlbumDetails(global::Server.AlbumRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAlbumDetails(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a music request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Server.AlbumDetails GetAlbumDetails(global::Server.AlbumRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAlbumDetails, null, options, request);
      }
      /// <summary>
      /// Sends a music request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Server.AlbumDetails> GetAlbumDetailsAsync(global::Server.AlbumRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAlbumDetailsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a music request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Server.AlbumDetails> GetAlbumDetailsAsync(global::Server.AlbumRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAlbumDetails, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MusicServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MusicServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MusicServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAlbumDetails, serviceImpl.GetAlbumDetails).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MusicServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetAlbumDetails, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Server.AlbumRequest, global::Server.AlbumDetails>(serviceImpl.GetAlbumDetails));
    }

  }
}
#endregion
